name: docdoc
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  build_runner: ^2.4.11
  cached_network_image: ^3.4.0
  chips_choice: ^3.0.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  date_picker_timeline: ^1.2.6
  dio: ^5.5.0+1
  easy_date_timeline: ^1.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_rating: ^2.0.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_maps_flutter: ^2.9.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.4.0
  read_more_text: ^0.0.5
  readmore: ^3.0.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
